### ISSUE TITLE
please support oled 0.96

### ISSUE THREAD

**Issue by mikerc2017** [sfrwmaker/soldering_907_lcd#1]
please support oled 0.96 or 0.91.
 lcd  1602 or 0802  with 7805 is so hot

**Comment by mikerc2017** [comment]
help me

**Comment by sfrwmaker** [comment]
Hello!
Unfortunately, the graphic library (u8glib or so) cannot fit into the arduino memory. The only solution is a lcd display. I advise you to use dc-dc converter instead of linear regulator.

**Comment by mikerc2017** [comment]
> Hello!
> Unfortunately, the graphic library (u8glib or so) cannot fit into the arduino memory. The only solution is a lcd display. I advise you to use dc-dc converter instead of linear regulator.

So sad 
i remember your code compile about 22k 
Lcd1602 and 0802  so big size  and waste power .
